version: '3.8'

services:
  frontend:
    build:
      context: ./daw_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./daw_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./daw_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./daw_backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=daw_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=daw_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: