version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daw_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: rubenalvarezdev/daw_ruben_alvarez:dev
    ports:
      - "5173:5173"
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: daw_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data: