services:
  app:
    image: rubenalvarezdev/daw_ruben_alvarez:dev
    ports:
      - "5173:5173"  # Frontend
      - "8000:8000"  # Backend
    volumes:
      - ./daw_frontend:/var/www/frontend
      - ./daw_backend:/var/www/html
      - /var/www/frontend/node_modules
      - /var/www/html/vendor
    environment:
      - VITE_API_URL=http://localhost:8000
      - APP_KEY=base64:KjvPpVC/shpL7vqGzmJRf/7brbCkxEu+P8CJV8X1tVQ=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=daw_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=LA9ny76ISxXEYEqGVP8agEkmJk2H9kOS6JpX4sure9jJEloSjjjQeg2zjEoR415q
      - JWT_ALGO=HS256
    depends_on:
      db:
        condition: service_healthy
    networks:
      - daw_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=daw_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-proot", "-e", "SELECT 1"]
      interval: 2s
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - daw_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - daw_network

networks:
  daw_network:
    driver: bridge

volumes:
  mysql_data: